# Generated by Django 2.1.4 on 2018-12-17 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icallback_app', '0002_widgets_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callId', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.RenameModel(
            old_name='Widgets',
            new_name='Widget',
        ),
        migrations.AddField(
            model_name='call',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='icallback_app.Widget'),
        ),
    ]
