# Generated by Django 2.1.4 on 2018-12-17 17:35

from django.db import migrations, models
import icallback_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('icallback_app', '0003_auto_20181217_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='client_number',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='operator_number',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[(icallback_app.models.CallStatusType('OPERATOR_ANSWERED'), 'OPERATOR_ANSWERED'), (icallback_app.models.CallStatusType('CLIENT_ANSWERED'), 'CLIENT_ANSWERED'), (icallback_app.models.CallStatusType('NO_ANSWER'), 'NO_ANSWER'), (icallback_app.models.CallStatusType('FAILED'), 'FAILED')], max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='time_answered',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='time_ended',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='time_started',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
